const DATA = {
  contacts: [
    {
      brand: 'steam',
      label: 'Steam',
      nick: 'Dinouseg',
      url: 'https://steamcommunity.com/id/Dinouseg/',
    },
    {
      brand: 'discord',
      label: 'Discord',
      nick: 'dinouseg',
      url: 'https://discord.com/users/1066483005234888804',
    },
    {
      brand: 'tidal',
      label: 'Tidal',
      nick: 'Dinouseg',
      url: 'https://tidal.com/browse/user/Dinouseg',
    },
    {
      brand: 'instagram',
      label: 'Instagram',
      nick: '@dinouseg',
      url: 'https://instagram.com/dinouseg',
    },
    {
      brand: 'xbox',
      label: 'Xbox',
      nick: 'Dinouseg',
      url: 'https://account.xbox.com/profile?gamertag=dinouseg',
    },
    {
      brand: 'roblox',
      label: 'Roblox',
      nick: 'Dinouseg',
      url: 'https://www.roblox.com/users/4658779447/profile',
    },
    {
      brand: 'youtube',
      label: 'YouTube',
      nick: '@Dinouseg',
      url: 'https://youtube.com/@dinouseg',
    },
    {
      brand: 'gmail',
      label: 'Gmail',
      nick: 'dinouseg@gmail.com',
      url: 'mailto:dinouseg@gmail.com',
    },
  ],

  goalHours: 1000,
  goalTrophies: 200000,
  games: [
    {
      name: 'Minecraft',
      hours: 7800,
      tags: ['Survival', 'Economy', 'Developer'],
      img: 'fotky/minecraft.png',
      desc: '<strong>Minecraft</strong> is game I played the most. I was at my peak during the quarantine on <strong>Halmine</strong>.',
      gallery: [
        'fotky/deconomy1.png',
        'fotky/deconomy2.png',
        'fotky/deconomy3.png',
        'fotky/deconomy4.png',
      ],
    },
    {
      name: 'FiveM',
      hours: 850,
      tags: ['TrinityRP', 'VertexRP', 'Military'],
      img: 'fotky/fivem.png',
      desc: 'I started sweating <strong>FiveM</strong> in September 2025, and after a break in January, I have Comeback on <strong>VertexRP</strong>.',
      gallery: [
        'fotky/fivem1.png',
        'fotky/fivem2.png',
        'fotky/fivem3.png',
        'fotky/fivem4.png',
      ],
    },
    {
      name: 'Brawl Stars',
      trophy: 17000,
      tags: ['Mobile', 'Strategy', 'Competitive'],
      img: 'fotky/brawlstars.png',
      desc: '<strong>Brawl Stars</strong> is a game I play with my buddies at school.',
      gallery: [
        'fotky/brawlstars1.png',
        'fotky/brawlstars2.png',
        'fotky/brawlstars3.png',
        'fotky/brawlstars4.png',
      ],
    },
  ],

  music: [
    {
      title: 'HAY LUPITA',
      artist: 'LOMIIEL',
      thumb: 'fotky/song1.jpg',
      url: 'https://www.youtube.com/watch?v=-82WWzgQgaw&list=RD-82WWzgQgaw&start_radio=1',
    },
    {
      title: 'Te Quería Ver',
      artist: 'Alemán, Neton Vega',
      thumb: 'fotky/song2.jpg',
      url: 'https://www.youtube.com/watch?v=Yjwmq5_vilc&list=RDYjwmq5_vilc&start_radio=1',
    },
    {
      title: ' +57',
      artist: 'KAROL G, Feid, DFZM',
      thumb: 'fotky/song3.jpg',
      url: 'https://www.youtube.com/watch?v=5r5UePOgMQU&list=RD5r5UePOgMQU&start_radio=1',
    },
    {
      title: 'Q U E V A S H A C E R H O Y ?',
      artist: 'Omar Courtz',
      thumb: 'fotky/song4.jpg',
      url: 'https://www.youtube.com/watch?v=oD9rgl6kgWA&list=RDoD9rgl6kgWA&start_radio=1',
    },
    {
      title: 'MAMAZOTA',
      artist: 'ARLENE MC',
      thumb: 'fotky/song5.jpg',
      url: 'https://www.youtube.com/watch?v=n1Ttq-YzFU4&list=RDn1Ttq-YzFU4&start_radio=1',
    },
  ],

  projects: [
    {
      name: 'DinBot',
      sub: 'Discord Bot',
      color: '#5865F2',
      desc: 'A custom-programmed Discord bot for moderating my Discord server',
      icon: 'fotky/dinbot.png',
      iconLetter: 'D',
    },
    {
      name: 'Deconomy',
      sub: 'Minecraft Server',
      color: '#5cb85c',
      desc: 'A Survival Economy Minecraft server for my friends with tons of plugins ~ it took over six months to build',
      icon: 'fotky/deconomy.png',
      iconLetter: 'D',
    },
  ],

  pricing: [
    {
      tier: 'Basic',
      name: 'One-Pager',
      priceOriginal: 159,
      price: 129,
      priceNote: 'one-time',
      features: [
        'Single-page static website',
        'Fully responsive (mobile & desktop)',
        'Dark mode design',
        'Your info, contacts & socials',
        'Basic hover animations',
      ],
      cta: "I'm interested",
      url: 'index.html#kontakty',
      highlight: false,
    },
    {
      tier: 'Standard',
      name: 'Portfolio',
      priceOriginal: 399,
      price: 239,
      priceNote: 'one-time',
      features: [
        'Multi-page website',
        'Smooth scroll & hover animations',
        'Custom fonts and color palette',
        'Image gallery + social cards',
        'Contact section with form',
        'SEO optimization',
        'Custom domain setup',
        '14 days of free support',
      ],
      cta: "I'm interested",
      url: 'index.html#kontakty',
      highlight: true,
      badge: 'Most popular',
    },
    {
      tier: 'Premium',
      name: 'All-in-One',
      price: 'Custom',
      priceNote: 'by agreement',
      features: [
        'Built exactly the way you want it',
        'Premium effects (stars, lava lamp, glassmorphism)',
        'Editable data files — update content yourself',
        'Animated transitions & micro-interactions',
        'Custom illustrations or designs',
        'Custom domain + full deployment',
        'Priority support & free updates',
      ],
      cta: "Let's talk",
      url: 'index.html#kontakty',
      highlight: false,
    },
  ],

  hub: {
    image: 'fotky/hub.jpg',
    url: 'https://discord.gg/NkPKnqQEHQ',
    desc: "Gaming HUB is a closed community of my closest friends. Membership isn't guaranteed it's reserved for a select few.",
  },
};

const ICONS = {
  discord: 'fotky/discord_logo.png',
  roblox: 'fotky/roblox_logo.png',
  tidal: 'fotky/tidal_logo.png',
  steam: 'fotky/steam_logo.png',
  instagram: 'fotky/instagram_logo.png',
  xbox: 'fotky/xbox_logo.png',
  youtube: 'fotky/youtube_logo.png',
  gmail: 'fotky/gmail_logo.png',
};
